### ISSUE TITLE
jodis支持redis设置密码吗

### ISSUE THREAD

**Issue by tydldd** [wandoulabs/jodis#1]
1、jodis支持redis设置密码吗
2、codis可以使用密码访问redis， jodis连的codis，怎么就是验证密码失败呢

**Comment by Apache9** [comment]
还不支持。。。
等我加上之后发个新版本吧。。。

**Comment by Apache9** [comment]
用0.2.1吧，我发到 https://oss.sonatype.org 上了。

**Comment by tydldd** [comment]
稳定不

**Comment by Apache9** [comment]
没有大变化，就是改了一下创建的方式，你试一下能连上就没问题

**Comment by tydldd** [comment]
我看了就剩一个构造器没有被遗弃，新构造器传的参数还挺多的，麻烦点

**Comment by Apache9** [comment]
那个是private的，不是直接给外部用的，外部创建用Builder来建。。。

**Comment by tydldd** [comment]
...好吧。用0.2.0调好了。下个版本再换吧
