### ISSUE TITLE
jodis编译

### ISSUE THREAD

**Issue by lirs72379** [wandoulabs/jodis#5]
你好，jodis你们有提供JDK1.6的版本么？如果要弄1.6版本的话，重新编译jodis，JDK要用1.6的么?那rt.jar的包，缺少的文件要怎么弄呢？

**Comment by Apache9** [comment]
java6应该就是缺ThreadLocalRandom吧，这个改改直接用Random就好，其他还有啥问题？

**Comment by lirs72379** [comment]
你好，一个redis有15个db节点，jodis能不能自己去选择存储哪个节点。。。

**Comment by Apache9** [comment]
jodis是用来连codis的proxy的，不是直接连redis的呀。。。
