### ISSUE TITLE
curatorClient  zkserver  list

### ISSUE THREAD

**Issue by hea** [wandoulabs/jodis#6]
您好，请问java 客户端在连接的时候 如何连接 zklist

比如 kafka 在连接zk的时候  有个 zookeeper.connect  的写法是 ip:port,ip2,port,ip3:port
jodis 支持zklist吗

如果不支持,那客户端是如何连接多个proxy的

**Comment by Apache9** [comment]
支持，一样的写法

**Comment by hea** [comment]
谢谢 
JedisResourcePool jedisPool = RoundRobinJedisPool.create()
                .curatorClient("zkserver1:2181,zkserver2:2181,zkserver3:2181", 30000).zkProxyDir("/zk/codis/db_xxx/proxy").build();
